name: GSA_markets
channels: [conda-forge,  nodefaults]
dependencies:
  - python=3.11.*
  - pandas=1.5.*
  - jupyterlab=3.*
  - brightway2_nosolver=2.4.*
  - scikit-umfpack=0.3.*
  # numpy 1.26 has an error when trying to import umfpack
  - numpy=1.24.*
  - seaborn=*
  - pip=24.*
  - doit=0.33.*
  - numpy=1.20.*
  - scipy=1.*
  - matplotlib=3.3.*
  - jupyter-book=0.13.*
  - jupytext=1.13.*
  - notebook=6.2.*
  - pip:
      # Install presamples from git so compatible with Python 3.9+
      - https://github.com/PascalLesage/presamples/archive/3e7bfebb15dda2070621a2fcc12b789b0ebf2f27.zip
